### ISSUE TITLE
os.chdir('/Users/farismismar/Dropbox/Stock Trading Using ML')

### ISSUE THREAD

**Issue by RHK-MICROVERSE** [farismismar/Stock-Prediction#1]
Can you please kind enough to tell me what is inside it?
Everything I worked out up to line 411.
But I cannot draw starting line 413 "# Plot the data closing"
The out put is as follows:
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\backends\_backend_tk.py", line 259, in resize
    self.draw()
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\backends\backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\axes\_base.py", line 2607, in draw
    self._update_title_position(renderer)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\axes\_base.py", line 2556, in _update_title_position
    if title.get_window_extent(renderer).ymin < top:
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\backends\backend_agg.py", line 201, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\texmanager.py", line 308, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because latex could not be found
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\texmanager.py", line 304, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\backends\_backend_tk.py", line 338, in idle_draw
    self.draw()
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super(FigureCanvasTkAgg, self).draw()
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\backends\backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\axes\_base.py", line 2607, in draw
    self._update_title_position(renderer)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\axes\_base.py", line 2556, in _update_title_position
    if title.get_window_extent(renderer).ymin < top:
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\text.py", line 890, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\text.py", line 291, in _get_layout
    ismath="TeX" if self.get_usetex() else False)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\backends\backend_agg.py", line 201, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\texmanager.py", line 448, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\texmanager.py", line 338, in make_dvi
    texfile], tex)
  File "C:\ProgramData\Anaconda3\envs\DarwinexLabs\lib\site-packages\matplotlib\texmanager.py", line 308, in _run_checked_subprocess
    'found'.format(command[0])) from exc
RuntimeError: Failed to process string with tex because latex could not be found

Process finished with exit code 0

**Comment by RHK-MICROVERSE** [comment]
os.chdir('/Users/farismismar/Dropbox/Stock Trading Using ML')

**Comment by farismismar** [comment]
You do not need to know what is in that folder.  The other error you are getting is due to you not having TeX extensions installed in your computer.  You can just comment out the lines that request `usetex`.  I modified the code to remove these lines.
